### ISSUE TITLE
Penny Pincher not working.

### ISSUE THREAD

**Issue by KroLeXz** [goatcorp/DalamudPlugins#326] opened 2020-10-14 13:19 UTC
I think Penny Pincher needs to be updated

**Comment by ackwell** [comment] 2020-10-14 14:23
Which would be neither an issue with Dalamud, nor an issue with its plugin framework. Please file issues for specific plugins with the plugin itself.

**Comment by tesu** [comment] 2020-10-14 14:51
dupe of https://github.com/tesu/PennyPincher/issues/2

**Closed** 2020-12-09 19:06 UTC
